Repository sayingpotato/Backend, pull requests merged in 2023-05, with the labels that each got.

#47 update : add CustomerImageServiceTest (#39)
  src/test/java/iampotato/iampotato/domain/customer/application/CustomerImageServiceTest.java
Labels: ✅ Test

#49 Deploy/migrate to new cloud(#48)
  .github/workflows/cicd.yml
  src/main/resources/application-dev.yml
Labels: 🌏 Deploy

#50 Feat/develop store detail(#46)
  src/main/java/iampotato/iampotato/domain/discount/domain/Discounts.java
  src/main/java/iampotato/iampotato/domain/item/domain/Item.java
  src/main/java/iampotato/iampotato/domain/item/domain/Items.java
  src/main/java/iampotato/iampotato/domain/review/domain/Review.java
  src/main/java/iampotato/iampotato/domain/review/domain/ReviewResultOfCafe.java
  src/main/java/iampotato/iampotato/domain/review/domain/Reviews.java
  src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
  src/main/java/iampotato/iampotato/domain/store/application/StoreService.java
  src/main/java/iampotato/iampotato/domain/store/dao/StoreRepository.java
  src/main/java/iampotato/iampotato/domain/store/domain/Store.java
  src/main/java/iampotato/iampotato/domain/store/domain/StoreDay.java
  src/main/java/iampotato/iampotato/domain/store/dto/StoreMapListDiscount.java
  src/main/java/iampotato/iampotato/domain/store/dto/StoreMarkerInfo.java
  src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailDiscount.java
  src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailItemOptions.java
  src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailItems.java
  src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailRequest.java
  src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailResponse.java
  src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailStoreImage.java
  src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailStoreOperationHour.java
  src/main/java/iampotato/iampotato/domain/store/dto/map/StoreMapRequest.java
  src/main/java/iampotato/iampotato/domain/store/dto/map/StoreMapResponse.java
  src/main/java/iampotato/iampotato/domain/store/dto/map/StoreMarkerInfo.java
  src/main/java/iampotato/iampotato/domain/store/dto/map/StoreMarkerOperationHour.java
  src/main/java/iampotato/iampotato/domain/store/dto/maplist/StoreMapListDiscount.java
  src/main/java/iampotato/iampotato/domain/store/dto/maplist/StoreMapListRequest.java
  src/main/java/iampotato/iampotato/domain/store/dto/maplist/StoreMapListResponse.java
  src/main/java/iampotato/iampotato/domain/store/dto/register/StoreRegistrationRequest.java
  src/main/java/iampotato/iampotato/domain/store/dto/register/StoreRegistrationResponse.java
  src/main/java/iampotato/iampotato/domain/store/dto/todaydiscount/StoreTodayDiscountRequest.java
  src/main/java/iampotato/iampotato/domain/store/dto/todaydiscount/StoreTodayDiscountResponse.java
  src/main/java/iampotato/iampotato/domain/storeimage/domain/StoreImage.java
  src/main/java/iampotato/iampotato/domain/storeimage/domain/StoreImages.java
  src/main/java/iampotato/iampotato/domain/storeoperationhour/domain/StoreOperationHour.java
  src/main/java/iampotato/iampotato/domain/storeoperationhour/domain/StoreOperationHours.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API

#53 Feat/make exception strategy(#52)
  src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
  src/main/java/iampotato/iampotato/domain/store/application/StoreService.java
  src/main/java/iampotato/iampotato/domain/store/dao/StoreRepository.java
  src/main/java/iampotato/iampotato/domain/store/dto/todaydiscount/StoreTodayDiscountRequest.java
  src/main/java/iampotato/iampotato/domain/store/exception/StoreException.java
  src/main/java/iampotato/iampotato/domain/store/exception/StoreExceptionGroup.java
  src/main/java/iampotato/iampotato/global/exception/ExceptionController.java
  src/main/java/iampotato/iampotato/global/exception/ValidExceptionGroup.java
  src/main/java/iampotato/iampotato/global/util/ErrorResult.java
  src/main/java/iampotato/iampotato/global/util/Result.java
Labels: ⚙ Setting, ✨ Feature

#55 feat : add description (#52)
  src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
Labels: ⚙ Setting, 📬 API

#57 feat : add InitDb (#56)
  src/main/java/iampotato/iampotato/InitDb.java
Labels: ✅ Test

#58 Feature/apply jwt(#51)
  build.gradle
  src/main/java/iampotato/iampotato/domain/customer/api/CustomerApi.java
  src/main/java/iampotato/iampotato/domain/customer/application/CustomUserDetailsService.java
  src/main/java/iampotato/iampotato/domain/customer/application/CustomerImageService.java
  src/main/java/iampotato/iampotato/domain/customer/application/CustomerSignInService.java
  src/main/java/iampotato/iampotato/domain/customer/application/CustomerSignUpService.java
  src/main/java/iampotato/iampotato/domain/customer/dao/CustomerRepository.java
  src/main/java/iampotato/iampotato/domain/customer/domain/Customer.java
  src/main/java/iampotato/iampotato/domain/customer/dto/SignInRequest.java
  src/main/java/iampotato/iampotato/domain/customer/dto/SignUpResponse.java
  src/main/java/iampotato/iampotato/domain/customer/dto/TokenResponse.java
  src/main/java/iampotato/iampotato/domain/customer/dto/UploadImageResponse.java
  src/main/java/iampotato/iampotato/domain/customer/jwt/JwtAuthenticationFilter.java
  src/main/java/iampotato/iampotato/domain/customer/jwt/JwtTokenProvider.java
  src/main/java/iampotato/iampotato/global/config/SecurityConfig.java
  src/main/java/iampotato/iampotato/global/util/SecurityUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/iampotato/iampotato/domain/customer/application/CustomerImageServiceTest.java
  src/test/java/iampotato/iampotato/domain/customer/application/CustomerSignUpServiceTest.java
Labels: ✨ Feature, 📬 API

#59 fix : fix some errors about cors (#51)
  src/main/java/iampotato/iampotato/global/config/SecurityConfig.java
Labels: 🐞 BugFix, 📬 API

#61 feat : modify cors (#60)
  src/main/java/iampotato/iampotato/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#63 Refactor/apply global exception(#62)
  src/main/java/iampotato/iampotato/domain/customer/application/CustomerSignInService.java
  src/main/java/iampotato/iampotato/domain/customer/application/CustomerSignUpService.java
  src/main/java/iampotato/iampotato/domain/customer/domain/Customer.java
  src/main/java/iampotato/iampotato/domain/customer/exception/CustomerException.java
  src/main/java/iampotato/iampotato/domain/customer/exception/CustomerExceptionGroup.java
  src/main/java/iampotato/iampotato/global/exception/ExceptionController.java
Labels: 📬 API, 🔨 Refactor
